"""GROBID TEI parsing helpers for future PDF ingestion."""

from __future__ import annotations

from pathlib import Path
from xml.etree import ElementTree

from pydantic import BaseModel, Field


class GrobidSection(BaseModel):
    """A parsed TEI body section."""

    title: str
    text: str
    page_or_anchor: str = ""


class GrobidDocument(BaseModel):
    """Structured text extracted from a GROBID TEI document."""

    doc_id: str
    source_path: str
    title: str = ""
    abstract: str = ""
    sections: list[GrobidSection] = Field(default_factory=list)


class GrobidTeiParser:
    """Parse GROBID TEI XML into a small structured document."""

    def parse_text(self, tei_xml: str, *, doc_id: str, source_path: str = "") -> GrobidDocument:
        """Parse TEI XML content without requiring a live GROBID service."""

        root = ElementTree.fromstring(tei_xml)
        title = _first_text(root, ".//tei:titleStmt/tei:title")
        abstract = _joined_text(root, ".//tei:profileDesc/tei:abstract")
        sections: list[GrobidSection] = []
        for div in root.findall(".//tei:text/tei:body/tei:div", _NAMESPACES):
            head = _direct_child_text(div, "head") or "Untitled section"
            text = _joined_direct_paragraphs(div)
            if not text:
                continue
            sections.append(
                GrobidSection(
                    title=head,
                    text=text,
                    page_or_anchor=f"#{_slugify(head)}",
                )
            )
        return GrobidDocument(
            doc_id=doc_id,
            source_path=source_path,
            title=title,
            abstract=abstract,
            sections=sections,
        )

    def parse_file(self, path: Path | str, *, doc_id: str) -> GrobidDocument:
        """Parse a local TEI XML file generated by GROBID."""

        tei_path = Path(path)
        return self.parse_text(
            tei_path.read_text(encoding="utf-8"),
            doc_id=doc_id,
            source_path=str(tei_path).replace("\\", "/"),
        )


_NAMESPACES = {"tei": "http://www.tei-c.org/ns/1.0"}


def _first_text(root: ElementTree.Element, path: str) -> str:
    element = root.find(path, _NAMESPACES)
    if element is None:
        return ""
    return " ".join("".join(element.itertext()).split())


def _joined_text(root: ElementTree.Element, path: str) -> str:
    element = root.find(path, _NAMESPACES)
    if element is None:
        return ""
    return " ".join("".join(element.itertext()).split())


def _direct_child_text(element: ElementTree.Element, tag: str) -> str:
    child = element.find(f"tei:{tag}", _NAMESPACES)
    if child is None:
        return ""
    return " ".join("".join(child.itertext()).split())


def _joined_direct_paragraphs(element: ElementTree.Element) -> str:
    paragraphs = []
    for paragraph in element.findall("tei:p", _NAMESPACES):
        text = " ".join("".join(paragraph.itertext()).split())
        if text:
            paragraphs.append(text)
    return " ".join(paragraphs)


def _slugify(value: str) -> str:
    tokens = []
    current = []
    for character in value.lower():
        if character.isalnum():
            current.append(character)
            continue
        if current:
            tokens.append("".join(current))
            current = []
    if current:
        tokens.append("".join(current))
    return "-".join(tokens) or "section"
